/*
* generated by Xtext
*/
package org.robotframework.text.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SpaceOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
