/*
* generated by Xtext
*/
package org.robotframework.text.ui.contentassist;

import org.robotframework.text.ui.contentassist.AbstractSpaceProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SpaceProposalProvider extends AbstractSpaceProposalProvider {

}
